#!/usr/bin/env python3
"""
Build a print-quality PDF of 02_Learner_Workbook.md.

Pipeline:
  1. Render the Markdown to HTML with python-markdown (with the TOC extension).
  2. Wrap it in a styled HTML shell that uses the EdYoda paper/terra design
     system (Fraunces + Geist + Geist Mono, warm cream bg, terracotta accent),
     adds a cover page, and inserts the auto-generated TOC.
  3. Headless-Chrome --print-to-pdf the resulting HTML to a PDF.

The HTML file is also kept on disk for inspection.
"""

import os, re, subprocess, sys, html as html_lib
import markdown

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_MD = os.path.join(HERE, '02_Learner_Workbook.md')
OUT_HTML = os.path.join(HERE, 'Session4_Learner_Workbook_print.html')
OUT_PDF  = os.path.join(HERE, 'Session4_Learner_Workbook.pdf')

CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'

# ---------------------------------------------------------------------------
# 1. Read source markdown
# ---------------------------------------------------------------------------
with open(SRC_MD, 'r', encoding='utf-8') as f:
    src = f.read()

# Strip the duplicated front matter / colophon that's redundant in a PDF
# (header lines that recap "Session 4 of 8 · 120 min" sit just below H1).
# We keep the H1 itself — it lives on the cover page.

# Extract the H1 (first level-1 heading)
m = re.search(r'^#\s+(.+)$', src, re.M)
title = m.group(1).strip() if m else 'Lumière — Session 4 Learner Workbook'

# Build the body markdown (everything except the leading H1, which we render
# separately on the cover). Also strip the closing colophon — we put it in
# the PDF footer instead.
body_md = re.sub(r'^#\s+.+\n', '', src, count=1)
body_md = re.sub(
    r'\n+\*\*Written & facilitated by Shantanu Chandra.*?S04\*\*\s*$',
    '', body_md, flags=re.S)

# ---------------------------------------------------------------------------
# 2. Render markdown → HTML, with TOC
# ---------------------------------------------------------------------------
md = markdown.Markdown(
    extensions=['toc', 'tables', 'fenced_code', 'attr_list', 'sane_lists'],
    extension_configs={
        'toc': {
            'toc_depth': '2-3',
            'permalink': False,
            'anchorlink': False,
        },
    },
)
content_html = md.convert(body_md)
toc_html = md.toc      # generated by the toc extension

# The TOC extension outputs a <div class="toc">…</div>; strip the wrapper.
toc_inner = re.sub(r'^<div class="toc">|</div>\s*$', '', toc_html.strip()).strip()

# ---------------------------------------------------------------------------
# 3. Wrap in the EdYoda design-system HTML shell
# ---------------------------------------------------------------------------
HTML_SHELL = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{title}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght,SOFT,WONK@9..144,300..900,0..100,0..1&family=Geist:wght@300..700&family=Geist+Mono:wght@400;500;600&display=swap" rel="stylesheet">
<style>
:root {{
  --paper:       #f5efe6;
  --paper-warm:  #ede4d3;
  --paper-cream: #faf6ef;
  --ink:         #1a1814;
  --ink-soft:    #4a463e;
  --ink-mute:    #8a8478;
  --ink-faint:   #b8b1a3;
  --rule:        #d4ccba;
  --rule-soft:   #e3dccb;
  --terra:       #b8431b;
  --terra-soft:  rgba(184, 67, 27, 0.10);
  --terra-deep:  #8c2e10;
  --gold:        #a16207;
  --leaf:        #5a7a3c;
}}

@page {{
  size: A4;
  margin: 22mm 18mm 22mm 18mm;

  @bottom-left {{
    content: "Lumière · Session 4 · RAG";
    font-family: 'Geist Mono', monospace;
    font-size: 7.5pt;
    color: #8a8478;
    letter-spacing: 0.12em;
    text-transform: uppercase;
  }}
  @bottom-right {{
    content: counter(page);
    font-family: 'Fraunces', serif;
    font-size: 10pt;
    color: #8a8478;
  }}
}}
@page :first {{
  margin: 0;
  @bottom-left {{ content: ""; }}
  @bottom-right {{ content: ""; }}
}}
@page toc {{
  @bottom-left {{ content: "Table of Contents"; }}
}}

* {{ box-sizing: border-box; margin: 0; padding: 0; }}

html, body {{
  background: var(--paper);
  color: var(--ink);
  font-family: 'Geist', -apple-system, BlinkMacSystemFont, system-ui, sans-serif;
  font-size: 10.5pt;
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}}

/* ── Cover ─────────────────────────────────────────────────────────── */
.cover {{
  page: first;
  width: 210mm; height: 297mm;
  background: var(--paper);
  position: relative;
  padding: 28mm 24mm;
  display: flex; flex-direction: column;
  page-break-after: always;
}}
.cover::before {{
  /* subtle paper grain */
  content: ''; position: absolute; inset: 0; pointer-events: none;
  opacity: 0.30; mix-blend-mode: multiply; z-index: 0;
  background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='3' stitchTiles='stitch'/%3E%3CfeColorMatrix values='0 0 0 0 0.10 0 0 0 0 0.09 0 0 0 0 0.07 0 0 0 0.5 0'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.55'/%3E%3C/svg%3E");
}}
.cover-inner {{
  position: relative; z-index: 1;
  display: flex; flex-direction: column;
  height: 100%;
}}
.cover .eyebrow {{
  font-family: 'Geist Mono', monospace;
  font-size: 8.5pt; letter-spacing: 0.30em; text-transform: uppercase;
  color: var(--terra); font-weight: 500; padding-left: 36pt;
  position: relative;
}}
.cover .eyebrow::before {{
  content: ''; position: absolute; left: 0; top: 50%;
  width: 28pt; height: 1px; background: var(--terra);
}}
.cover .vol {{
  margin-top: 14pt;
  font-family: 'Geist Mono', monospace;
  font-size: 8pt; letter-spacing: 0.16em; text-transform: uppercase;
  color: var(--ink-mute);
}}
.cover h1 {{
  margin-top: auto;
  font-family: 'Fraunces', serif;
  font-weight: 300;
  font-size: 62pt; line-height: 0.96; letter-spacing: -0.025em;
  font-variation-settings: 'opsz' 144, 'SOFT' 50, 'WONK' 1;
  color: var(--ink);
  max-width: 14ch;
}}
.cover h1 em {{
  font-style: italic; color: var(--terra);
  font-variation-settings: 'opsz' 144, 'SOFT' 50, 'WONK' 1;
}}
.cover .cover-lede {{
  font-family: 'Fraunces', serif; font-style: italic; font-weight: 300;
  font-size: 14pt; line-height: 1.4; color: var(--ink-soft);
  font-variation-settings: 'opsz' 36;
  max-width: 50ch; margin-top: 18pt;
}}
.cover .cover-foot {{
  margin-top: 32pt; padding-top: 12pt;
  border-top: 1px solid var(--ink);
  display: flex; justify-content: space-between; align-items: baseline;
  font-family: 'Geist Mono', monospace; font-size: 8pt;
  letter-spacing: 0.14em; text-transform: uppercase; color: var(--ink-mute);
}}
.cover .cover-foot .name {{
  font-family: 'Fraunces', serif; font-style: italic; font-size: 11pt;
  letter-spacing: 0; text-transform: none; color: var(--ink);
}}

/* ── TOC ──────────────────────────────────────────────────────────── */
.toc-page {{
  page: toc;
  page-break-before: always;
  page-break-after: always;
  padding: 14mm 4mm;
}}
.toc-page h2 {{
  font-family: 'Fraunces', serif; font-weight: 400;
  font-size: 28pt; line-height: 1.05; color: var(--ink);
  font-variation-settings: 'opsz' 80, 'SOFT' 30;
  margin-bottom: 4pt;
}}
.toc-page h2 em {{ font-style: italic; color: var(--terra); }}
.toc-page .toc-eyebrow {{
  font-family: 'Geist Mono', monospace; font-size: 8pt;
  letter-spacing: 0.22em; text-transform: uppercase;
  color: var(--terra); font-weight: 500;
  margin-bottom: 12pt; padding-left: 36pt; position: relative;
}}
.toc-page .toc-eyebrow::before {{
  content: ''; position: absolute; left: 0; top: 50%;
  width: 28pt; height: 1px; background: var(--terra);
}}
.toc-list {{
  margin-top: 18pt;
  border-top: 2px solid var(--ink);
  padding-top: 14pt;
}}
.toc-list ul {{ list-style: none; margin: 0; padding: 0; }}
.toc-list > ul > li {{
  padding: 6pt 0;
  border-bottom: 1px dotted var(--rule);
}}
.toc-list > ul > li > a {{
  font-family: 'Fraunces', serif;
  font-size: 13pt; font-weight: 400; color: var(--ink);
  text-decoration: none; line-height: 1.3;
  font-variation-settings: 'opsz' 36;
}}
.toc-list ul ul {{
  margin: 4pt 0 4pt 16pt;
  padding-left: 12pt; border-left: 1px solid var(--rule-soft);
}}
.toc-list ul ul li {{
  padding: 2pt 0;
  font-family: 'Geist', sans-serif;
}}
.toc-list ul ul li a {{
  font-size: 9.5pt; color: var(--ink-soft); text-decoration: none;
}}
.toc-list ul ul li a:hover {{ color: var(--terra); }}
.toc-list a {{ color: inherit; text-decoration: none; }}

/* ── Body content ─────────────────────────────────────────────────── */
.content {{
  padding: 4mm;
  page-break-before: always;
}}
/* Major sections (h2) — start on a new page only for the "big" sections;
   short sections like Troubleshooting can flow inline to avoid huge gaps.
   We tag the big ones via .h2-major in post-processing. */
.content h2 {{
  page-break-after: avoid;
  font-family: 'Fraunces', serif;
  font-weight: 400; font-size: 24pt; line-height: 1.1;
  color: var(--ink); margin: 28pt 0 4pt 0;
  font-variation-settings: 'opsz' 80, 'SOFT' 30;
  padding-bottom: 8pt; border-bottom: 1px solid var(--rule);
}}
.content h2.h2-major {{
  page-break-before: always;
  margin-top: 0;
}}
.content h2:first-of-type {{ page-break-before: avoid; margin-top: 0; }}
.content h2 em {{ font-style: italic; color: var(--terra); }}
.content h3 {{
  page-break-after: avoid;
  font-family: 'Fraunces', serif;
  font-weight: 500; font-size: 14pt; line-height: 1.25;
  color: var(--ink); margin: 16pt 0 4pt 0;
}}
.content h3 em {{ font-style: italic; color: var(--terra); }}
.content h4 {{
  page-break-after: avoid;
  font-family: 'Geist Mono', monospace;
  font-size: 8.5pt; letter-spacing: 0.14em; text-transform: uppercase;
  font-weight: 600; color: var(--ink-mute);
  margin: 12pt 0 4pt 0;
}}

.content p {{
  margin: 6pt 0; orphans: 3; widows: 3;
  font-size: 10.5pt; line-height: 1.6; color: var(--ink);
}}
.content em {{ font-style: italic; color: var(--ink); }}
.content strong {{ color: var(--ink); font-weight: 600; }}
.content a {{ color: var(--terra); text-decoration: none; }}

.content ul, .content ol {{
  margin: 6pt 0 6pt 18pt; padding: 0;
}}
.content li {{
  margin: 2pt 0; line-height: 1.55;
  font-size: 10.5pt; color: var(--ink);
}}
.content li::marker {{ color: var(--terra); }}

.content blockquote {{
  margin: 10pt 0;
  padding: 8pt 14pt;
  background: var(--paper-cream);
  border-left: 3px solid var(--terra);
  font-family: 'Fraunces', serif; font-style: italic;
  color: var(--ink-soft); font-size: 10.5pt; line-height: 1.55;
  font-variation-settings: 'opsz' 36;
}}
.content blockquote p {{ margin: 0; font-style: italic; color: var(--ink-soft); }}

.content hr {{
  margin: 18pt 0; border: none;
  border-top: 1px solid var(--rule);
}}

/* code blocks (the two prompts + the architecture diagram).
   We use pre-wrap by default so long prompt lines soft-wrap inside the dark
   panel (no clipping). The architecture ASCII diagram needs whitespace
   preserved EXACTLY — it's tagged with .ascii via post-processing and
   reverts to white-space: pre. */
.content pre {{
  background: #1a1814;            /* dark editorial mono panel */
  color: #f5efe6;
  padding: 12pt 14pt;
  border-radius: 3px;
  font-family: 'Geist Mono', monospace;
  font-size: 8pt; line-height: 1.55;
  white-space: pre-wrap;          /* soft-wrap long lines, don't clip */
  word-break: break-word;
  overflow-wrap: anywhere;
  page-break-inside: avoid;       /* try not to split mid-prompt */
  margin: 10pt 0;
}}
.content pre code {{
  background: transparent; color: inherit;
  font-family: inherit; font-size: inherit;
  padding: 0;
  white-space: inherit;
  word-break: inherit;
  overflow-wrap: inherit;
}}
/* ASCII diagrams (architecture, fillable KB sheet, etc.) — preserve exact
   whitespace, allow page break for the giant ones. */
.content pre.ascii {{
  white-space: pre;
  word-break: normal;
  overflow-wrap: normal;
  font-size: 7.5pt; line-height: 1.35;
}}
.content pre.ascii.allow-break {{ page-break-inside: auto; }}

.content code {{
  background: var(--paper-warm);
  color: var(--terra-deep);
  padding: 1pt 4pt; border-radius: 2px;
  font-family: 'Geist Mono', monospace;
  font-size: 9pt;
}}

/* tables */
.content table {{
  width: 100%; border-collapse: collapse;
  margin: 10pt 0; font-size: 9.5pt;
  page-break-inside: avoid;
}}
.content table th {{
  text-align: left; padding: 6pt 8pt;
  font-family: 'Geist Mono', monospace;
  font-size: 8pt; letter-spacing: 0.10em; text-transform: uppercase;
  color: var(--ink); font-weight: 600;
  border-bottom: 2px solid var(--ink); background: var(--paper-cream);
}}
.content table td {{
  padding: 6pt 8pt;
  border-bottom: 1px solid var(--rule-soft);
  color: var(--ink-soft); line-height: 1.5;
  vertical-align: top;
}}
.content table tr:last-child td {{ border-bottom: none; }}
.content table td strong, .content table td code {{ color: var(--ink); }}

/* Avoid orphaned headings — the heading and the first paragraph after it
   must travel together, never split across pages. */
.content h2 + p, .content h3 + p, .content h4 + p {{ page-break-before: avoid; }}

/* Keep a sub-heading + its lead paragraph + a following code block on the
   same page when possible. CSS `break-before: avoid` on the pre that
   immediately follows a heading is the precise version. */
.content h3 + p + pre,
.content h3 + pre,
.content h4 + p + pre,
.content h4 + pre {{
  page-break-before: avoid;
}}

/* ── Write-in fields (workbook-style fill-in lines) ─────────────────────
   We tag a paragraph as .writein in post-processing when the source uses
   the pattern **Log the answer here:** / **Paste the source line ...** /
   **After — what did the agent say?**. We then render the prompt PLUS
   three blank ruled lines underneath, so the printed PDF has real
   space for the learner to write. */
.content p.writein {{
  margin: 8pt 0 4pt 0;
  font-weight: 600;
  color: var(--ink);
}}
.content p.writein + .writein-lines {{
  margin: 0 0 14pt 0;
  page-break-inside: avoid;
}}
.content .writein-lines .ln {{
  display: block;
  height: 0;
  border-bottom: 1px solid var(--rule);
  margin: 14pt 0 0 0;
}}
.content .writein-lines .ln:first-child {{ margin-top: 8pt; }}
</style>
</head>
<body>

<!-- ===== COVER ===== -->
<section class="cover">
  <div class="cover-inner">
    <div class="eyebrow">EdYoda · Generative AI for Non-Coders</div>
    <div class="vol">Session 04 · Two-Hour Live · Learner Workbook</div>
    <h1>RAG —<br>a brain<br>of your <em>own</em><br>data.</h1>
    <p class="cover-lede">A field workbook for the Lumière build. Four personas. Five build steps. Three reference sheets. Two prompts to take home and rebuild it from scratch.</p>
    <div class="cover-foot">
      <span>No. 04 / Knowledge Agents</span>
      <span class="name">Shantanu Chandra</span>
      <span>linkedin.com/in/chandrashantanu</span>
    </div>
  </div>
</section>

<!-- ===== TABLE OF CONTENTS ===== -->
<section class="toc-page">
  <div class="toc-eyebrow">Inside this workbook</div>
  <h2>Table of <em>Contents.</em></h2>
  <div class="toc-list">
    {toc}
  </div>
</section>

<!-- ===== BODY ===== -->
<main class="content">
{content}
</main>

</body>
</html>
"""

# Strip H1 from rendered content (toc reflects only h2/h3 per config)
content_clean = re.sub(r'<h1[^>]*>.*?</h1>\s*', '', content_html, count=1, flags=re.S)

# Drop the trailing colophon `<hr>` we already stripped from markdown — be defensive
content_clean = re.sub(r'<hr\s*/?>\s*$', '', content_clean.strip())

# ── Post-processing pass: inject classes for page layout ───────────────
# Major-section H2s start on new pages; short ones (Troubleshooting,
# What's Next) flow inline to avoid huge empty pages.
MAJOR_H2_TITLES = {
    'The Lumière Knowledge Base — Key Facts at a Glance',
    'The Four Personas — Pick One',
    'Persona 1 — Last-minute Birthday',
    'Persona 2 — Allergy Parent',
    'Persona 3 — Corporate Bulk',
    'Persona 4 — Delivery Edge-case',
    'Reference Sheet 1 — Grounding Prompt Library',
    'Reference Sheet 2 — The RAG Dial',
    'Reference Sheet 3 — Knowledge Base Design Sheet',
    'Build Lumière yourself — two prompts, two stages',
    'What\'s Next — Session 5',
}
def _h2_class(m):
    raw_inner = m.group(2)
    # Strip tags + decode entities for a clean text match
    text = re.sub(r'<[^>]+>', '', raw_inner)
    text = (text.replace('&amp;', '&').replace('&lt;', '<')
                .replace('&gt;', '>').replace('&#39;', "'")
                .replace('&quot;', '"'))
    text = text.strip()
    is_major = text in MAJOR_H2_TITLES
    attrs = m.group(1) or ''
    if is_major:
        if 'class="' in attrs:
            attrs = re.sub(r'class="([^"]*)"', r'class="\1 h2-major"', attrs)
        else:
            attrs = attrs.rstrip() + ' class="h2-major"'
    return f'<h2{attrs}>{raw_inner}</h2>'

content_clean = re.sub(r'<h2([^>]*)>(.*?)</h2>',
                       _h2_class, content_clean, flags=re.S)

# Write-in fields — replace **Log the answer here:** style paragraphs with
# a p.writein + a .writein-lines block of 3 ruled blanks.
WRITEIN_PATTERNS = [
    'Log the answer here:',
    'Paste the source line the agent returned:',
    'After — what did the agent say?',
    'Before adding the refusal line — what did the agent say?',
]
for pat in WRITEIN_PATTERNS:
    # python-markdown renders **X** as <strong>X</strong> inside a <p>
    esc = re.escape(pat)
    rx = re.compile(
        r'<p>\s*<strong>\s*' + esc + r'\s*</strong>\s*</p>',
        re.IGNORECASE,
    )
    repl = (
        f'<p class="writein">{pat}</p>'
        '<div class="writein-lines">'
        '<span class="ln"></span><span class="ln"></span><span class="ln"></span>'
        '</div>'
    )
    content_clean = rx.sub(repl, content_clean)

# Tag the architecture diagram (and any other ASCII art) so its whitespace
# is preserved exactly. Heuristic: a <pre><code> containing box-drawing
# characters or pipe-and-dash separators is ASCII art.
def _ascii_class(m):
    body = m.group(0)
    if re.search(r'[│┌┐└┘├┤┬┴┼─━┃┏┓┗┛]|\|\s*\d|---+', body):
        # Allow break for very tall diagrams (>1200 chars in the body)
        cls = 'ascii allow-break' if len(body) > 1200 else 'ascii'
        body = re.sub(r'<pre>', f'<pre class="{cls}">', body, count=1)
    return body
content_clean = re.sub(r'<pre>.*?</pre>', _ascii_class,
                       content_clean, flags=re.S)

html_out = HTML_SHELL.format(
    title=html_lib.escape(title),
    toc=toc_inner if toc_inner else '<p><em>(empty)</em></p>',
    content=content_clean,
)

with open(OUT_HTML, 'w', encoding='utf-8') as f:
    f.write(html_out)
print(f'Wrote HTML: {OUT_HTML}  ({len(html_out):,} bytes)')

# ---------------------------------------------------------------------------
# 4. Headless Chrome → PDF
# ---------------------------------------------------------------------------
if not os.path.isfile(CHROME):
    print(f'Chrome not found at {CHROME}; HTML written but PDF not built.')
    sys.exit(0)

file_url = 'file://' + OUT_HTML
cmd = [
    CHROME,
    '--headless',
    '--disable-gpu',
    '--no-pdf-header-footer',
    '--print-to-pdf=' + OUT_PDF,
    '--print-to-pdf-no-header',
    '--virtual-time-budget=12000',  # let Google Fonts settle
    '--no-sandbox',
    file_url,
]
print('Running headless Chrome…')
r = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
if r.returncode != 0:
    print('STDOUT:', r.stdout)
    print('STDERR:', r.stderr)
    sys.exit(r.returncode)

size = os.path.getsize(OUT_PDF)
print(f'Wrote PDF:  {OUT_PDF}  ({size:,} bytes)')
